// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3hAuuWFBEsMu7DPr06sNTfVyuTfNthHw',
    appId: '1:930726885158:web:822c8e039f6f8bd131f3e7',
    messagingSenderId: '930726885158',
    projectId: 'chatapp-83661',
    authDomain: 'chatapp-83661.firebaseapp.com',
    storageBucket: 'chatapp-83661.firebasestorage.app',
    measurementId: 'G-NYQE58JF9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnTcRRXR1g3aRYAXpeOhirGhUgo_KJEf0',
    appId: '1:930726885158:android:104932ccc708d4a431f3e7',
    messagingSenderId: '930726885158',
    projectId: 'chatapp-83661',
    storageBucket: 'chatapp-83661.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp5db9vd3Y5fwbmW9ZLLl2VpUj4oHDp3M',
    appId: '1:930726885158:ios:aa1a870b50dbc87431f3e7',
    messagingSenderId: '930726885158',
    projectId: 'chatapp-83661',
    storageBucket: 'chatapp-83661.firebasestorage.app',
    iosBundleId: 'com.example.chaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp5db9vd3Y5fwbmW9ZLLl2VpUj4oHDp3M',
    appId: '1:930726885158:ios:aa1a870b50dbc87431f3e7',
    messagingSenderId: '930726885158',
    projectId: 'chatapp-83661',
    storageBucket: 'chatapp-83661.firebasestorage.app',
    iosBundleId: 'com.example.chaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3hAuuWFBEsMu7DPr06sNTfVyuTfNthHw',
    appId: '1:930726885158:web:e6b4bf255c61c1da31f3e7',
    messagingSenderId: '930726885158',
    projectId: 'chatapp-83661',
    authDomain: 'chatapp-83661.firebaseapp.com',
    storageBucket: 'chatapp-83661.firebasestorage.app',
    measurementId: 'G-4EQWSN97MF',
  );
}
